DjangoBootcampSample/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # url(r'.*', include('samplepolls.urls')),
    url(r'^samplepolls/', include('samplepolls.urls')), # adding now
    url(r'^admin/', admin.site.urls), # already set up
]

samplepolls/urls.py
from django.conf.urls import url
from . import views

app_name = 'samplepolls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]


# app_name = 'samplepolls'
# urlpatterns = [
#     url(r'^$', views.index, name='index'),
# # ex: /samplepolls/5/
#     url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
#     # ex: /polls/5/results/
#     url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
#     # ex: /polls/5/vote/
#     url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
# ]

samplepolls/models.py
from django.db import models
import datetime
from django.utils import timezone # for later

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


# Superuser
# user1
# password123

samplepolls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic


from .models import Choice, Question

class IndexView(generic.ListView):
    template_name = 'samplepolls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """ Return the last 5 pub'd qs"""
        return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'samplepolls/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'samplepolls/results.html'

# vote function stays the same
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    print("Voted for {}".format(question_id))
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'samplepolls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('samplepolls:results', args=(question.id,)))


# Create your views here.
# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     # template = loader.get_template('samplepolls/index.html')
#     context = {
#         'latest_question_list': latest_question_list
#     }
#     # return HttpResponse(template.render(context,request))
#     return render(request, 'samplepolls/index.html', context)
# # Check out the docs for more explanation of this

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     print("I'm looking at the detail of question {}".format(question_id))
#     return render(request, 'samplepolls/detail.html', {'question': question})


# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'samplepolls/results.html', {'question': question})

#
# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")
#
# def detail(request, question_id):
#     return HttpResponse("You're looking at question {}".format(question_id))

# def results(request, question_id):
#     response = "You're looking at the results of question {}"
#     return HttpResponse(response.format(question_id))

# def vote(request, question_id):
#     return HttpResponse("You're voting on question {}".format(question_id))
#

templates/samplepolls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'samplepolls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
         <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote" />
    </form>

</body>
</html>

templates/samplepolls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'samplepolls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

templates/samplepolls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'samplepolls:detail' question.id %}">Vote again?</a>
</body>
</html>